### ISSUE TITLE
peer to peer code review

### ISSUE THREAD

**Issue by george827** [ohyajk/Leaderboard#5]
Hi @ohyajk ,
### highlights
Great job so far, your work looks impressive
✅  Good commit history
✅ Great use of GitHub flow. 💯
✅ Your project is documented professionally. 📜
✅ Great UI design. 💻
### Optional suggestions

- [x] Your score list overflow is hidden, the first item not visible, Kindly remove the `align-items center` to fix this. 🙏 
- [x] Kindly ensure for your pull request that all linters are checked, Your lighthouse linter is not successful.

Happy codding 😄 😄

**Comment by ohyajk** [comment]
Thankyou @george827 @c00p75 for your valuable suggestions. I will definitely try to implement these changes.😊
